apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: enrichment-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: "{{ env:REDIS_HOST }}"
    - name: redisPassword
      value: ""
